name: Deploy

on:
  push:
    branches: [ main ]

  release:
    types: [ released ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: |
          echo "$ENV_FILE" > .env

          docker login docker.pkg.github.com --username $GITHUB_ACTOR --password ${{ secrets.GITHUB_TOKEN }}
          docker build --pull --target runner --file Dockerfile --tag "docker.pkg.github.com/$GITHUB_REPOSITORY/next" .
          docker push "docker.pkg.github.com/$GITHUB_REPOSITORY/next"

      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          source: ".env,docker-compose.yml"
          target: ${{ secrets.PATH }}

      - name: Rebuild Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            docker login docker.pkg.github.com --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }}
            cd ${{ secrets.PATH }} && docker-compose pull && docker-compose up -d --remove-orphans
